### ISSUE TITLE
Example in documentation uses non-existing function

### ISSUE THREAD

**Issue by bassages** [ropg/ezTime#12]
Under https://github.com/ropg/ezTime#secondchanged-and-minutechanged the example uses the `dateString` function, which does not exist.
I think it is supposed to be `dateTime` https://github.com/ropg/ezTime#datetime.

Thank you for this nice lib and the comprehensive documentation :smiley::thumbsup:

**Comment by ropg** [comment]
Whoops, thank you, fixed...
