### ISSUE TITLE
Is timeserver not responding?

### ISSUE THREAD

**Issue by andersbjn** [ropg/ezTime#122]
Is there some error with the server?
It doesn't respond to requests since around 10:30 Stockholm time?

**Comment by ropg** [comment]
> Is there some error with the server?
> It doesn't respond to requests since around 10:30 Stockholm time?

Correct, I'm upgrading... Sorry for the disruption...

**Comment by andersbjn** [comment]
Ok!
Thank you for the superquick response!
When do you think it will be up again?
Best regards, Anders

**Comment by ropg** [comment]
> Thank you for the superquick response!
> When do you yhink it will be up again?


It's up again.

**Comment by andersbjn** [comment]
Supermany thanks!
Best regards, Anders

**Comment by SergDfv** [comment]
https://github.com/ropg/ezTime/blob/7b3c8aa020be818ac149e0762543ac5e81ccfabe/src/ezTime.h#L153-L155

I can't get connection on the port 2342. But it was success on the port 2343. 
Could you return 2342, please? It's necessary for my devices. 
Thank you in advance!

**Comment by rvdbreemen** [comment]
@ropg can't resolve timezones anymore, so did your upgrade break stuff?

[21:51:50][  13976| 12440] updateSettin( 163): -> field[ntptimezone], newValue[CET]
[21:51:52][  13304| 12440] startNTP    ( 151): Error setting Timezone: Timeout
[21:51:52][  11960| 11144] startNTP    ( 169): UTC time  : Thursday, 16-Sep-2021 21:51:52 UTC
[21:51:52][  11960| 11144] startNTP    ( 170): local time: Thursday, 16-Sep-2021 21:51:52 UTC

The server retreive of TZ location fails...

**Comment by projectsun2** [comment]
Hello, The server retrieve of TZ location fails, no connection to UDP 2342

**Comment by andersbjn** [comment]
Hi!
Do you have any update of what has happened and when it will work again?
Best regards,
Anders

**Comment by TomasOq** [comment]
Hello, The server is currently not responding - do you know when it will be available again?
Thanks in advance.

**Comment by dos1** [comment]
FWIW https://github.com/ropg/ezTime/pull/123 makes setting a custom server easier.

**Comment by ropg** [comment]
Holy crap, the 2343 was a mistake on my end, and then I didn't check my computer again. I'm so, so sorry...

it should now be up at 2342. Please test.

Sorry...

(And yes, I think it would make sense to have a service like timezoned have more servers, but it's my own homebrew protocol instead of something standardized that has an RFC and all. Will work on putting it on the same box that hosts my backup nameserver so there's at least two.)

**Comment by SergDfv** [comment]
![изображение](https://user-images.githubusercontent.com/45270120/133783498-91f3e84a-cf7b-4d7c-820c-fda53d311c8a.png)
The port is still not open...

**Comment by andersbjn** [comment]
Now server is responding with timezone definition on port 2342 so it seems ok!
Thanks!

**Comment by projectsun2** [comment]
> 
> 
> ![изображение](https://user-images.githubusercontent.com/45270120/133783498-91f3e84a-cf7b-4d7c-820c-fda53d311c8a.png)
> The port is still not open...

You can´t scan UDP! Because it´s a connectionless protocol.

**Comment by ropg** [comment]
To check if it's working, use:

```bash
$ nc -u timezoned.rop.nl 2342
```

And then type any identifier and follow it with a Ctrl-D (and no return). You'll then see the timezone info right after what you typed:

```
londonOK Europe/London GMT0BST,M3.5.0/1,M10.5.0
```

**Comment by TheGroundZero** [comment]
> @ropg
> And yes, I think it would make sense to have a service like timezoned have more servers

Did a crude attempt here, putting your code in a container image.

https://github.com/TheGroundZero/ezTimeContainer
