### ISSUE TITLE
Changing to DST at wrong time.

### ISSUE THREAD

**Issue by mike-s123** [ropg/ezTime#28]
Just trying to test out code before a real summertime change. 

So, I'm doing testing by setting the TZ string to change to summertime a few minutes in the future, expecting to watch the change. But, when set slightly in the future, it changes immediately. It's not changing at the correct local time.

Right now, it's Monday, 04-Feb-2019, 23:something. (date is M2.1.1, in "Olson speak")

e.g.  With the string set to "EST5EDT,M2.1.2/4:13,M11.1.0"  (summertime begins at 04:13 tomorrow morning), it actually changes to DST at 23:08 local standard time, which is 5 minutes before when it should change if it were simply using UTC instead of local time! 100% repeatable, I can switch back and forth. If I set the TZ string to 5 hours and 4 minutes ahead of local time, it will change to DST. If I set it to 5 hours and 6 minutes ahead of local time, it will change to standard time.

Weird. I'm not a coder, I only play one on the Internet enough to be dangerous. But, that behavior would make sense if in the relevant routine, instead of subtracting 5 hours (the offset from UTC) from UTC time, you're subtracting 5 minutes (or something like that, my brain is starting to hurt).

**Comment by ropg** [comment]
I had a similar case of brain hurt trying to hunt down an issue that is probably the same thing (#15), but the swap with minutes and hours is fascinating and may be the best clue yet. I will take a look soon, there's clearly some bigger work to be done...

**Comment by ropg** [comment]
Fixed by commit a81250a70c896ed295452012798e1e00d34b847f from #29 (thanks!!)
