### ISSUE TITLE
makeOrdinalTime return wrong result

### ISSUE THREAD

**Issue by wayfarerbasta** [ropg/ezTime#38]
The function makeOrdinalTime returns 24th of March 2019 as the last (ordinal 5) Sunday of March. In my calendar the 31st March is th last Sunday. It seams that this is the reason for #31

**Comment by ropg** [comment]
Fixed by merging pull request (thank you @wayfarerbasta ). I currently believe this also fixes issue #41 #31 and #15, so am closing those. YAY!
