### ISSUE TITLE
All my clock based on this library started to show one hour more today

### ISSUE THREAD

**Issue by BugerDread** [ropg/ezTime#41]
I will write more details later as now I have different thing to do, but all my clock based on ESP8266 and this library are showing +1 hour (now is 12:47 here, clock shows 13:47). Im Europe / Prague TZ, manually set (not geoIP), tried to restart and received wrong time again.

**Comment by BugerDread** [comment]
maybe wrong info about our TZ because "summer time" starts next week here
http://www.timezoneconverter.com/cgi-bin/zoneinfo?tz=Europe/Prague

**Comment by Tederean** [comment]
Same problem here. Using Europe/Berlin shows active DST even though it's not 31-March or beyond.

**Comment by ropg** [comment]
I will release a new version of ezTime, hopefully tomorrow.

**Comment by ropg** [comment]
I believe this is fixed by the fix for #38, my makeOrdinalTime function was off when the last of a given weekday in a given month was requested. Please reopen if problem reoccurs.
