### ISSUE TITLE
Timezone definition incorrect

### ISSUE THREAD

**Issue by agoston** [ropg/ezTime#43]
Hi,

Awesome library, however, this week, a bug was revealed in timezone config.
In the README.md, and also in your lookup server, it is stated that timezone for Berlin/western eu is:

```
CET-1CEST,M3.4.0/2,M10.4.0/3
```

However, the actual definition is 'last sunday of the month'. In march 2019, the month had 5 sundays, so the clock on my night table is off for an hour this week.

According to the spec, '5' means 'last of the month', so I've also took the liberty to update the definition in my code to

```
CET-1CEST,M3.5.0/2,M10.5.0/3
```

Can you update README.md and probably your server accordingly?

**Comment by ropg** [comment]
If you upgrade to 0.7.10, you'll likely notice the problem is fixed...

**Comment by ropg** [comment]
Fixed the documentation now also...

**Comment by agoston** [comment]
drat, i did check the commits, but missed the "last week patch" comment, sorry.
Good to know it's fixed, thanks!
