### ISSUE TITLE
get  epoch in millis

### ISSUE THREAD

**Issue by ramarro123** [ropg/ezTime#5]
What's the correct way to get an epoch time from millis? (as javascript/java System.currentTimeMillis())

i am not 100% sure that it's now()*1000+ms() so i'll like to get confirmation :) 

tnx

**Comment by ropg** [comment]
You would need to store the result in a 64-bit variable, but if that's OK, I would do
```
[Timezone.]now() * 1000 + ms(LAST_READ)
```
 (The `LAST_READ` is to make sure that the milliseconds are takes from the time the whole seconds are read, to prevent the condition where the milliseconds would wrap between the two reads.
