### ISSUE TITLE
MKR1000 and MKR WiFi1010 - EEPROM

### ISSUE THREAD

**Issue by grezco** [ropg/ezTime#7]
Hello,
As indicate in the Readme file, to use the MKR familly, I commented the two lines : 
//#define EZTIME_CACHE_EEPROM
// #define EZTIME_CACHE_NVS

What is the impact of not using the epprom ?

**Comment by ropg** [comment]
My code can use either `EEPROM.h` or `Preferences.h`, the MKR comes with `FlashStorage.h`, which is a different interface to store values in EEPROM. You don't need to use the timezone info cache that is all this is used for. It is not as relevant as it used to be as we longer use timezoneapi.io but our own timezoned info service which does not have a set maximum number of requests.
