### ISSUE TITLE
bug where timezones not observing DST were incorrectly translated

### ISSUE THREAD

**Issue by johnslemmer** [ropg/ezTime#70]
Timezones like Pacific/Honolulu and America/Phoenix (and probably others) do not observe DST.  They always stay on their standard time.

The current code essentially treated all calls to `tzTime` in this time zone like the timestamp `t` was a UTC timestamp (subtracting the the offset).  However, this is incorrect and should be able to translate both ways depending on what `local_or_utc` is set to.

See https://github.com/ropg/ezTime/blob/master/src/ezTime.cpp#L752 for the bug.

PR coming soon for the fix.

**Comment by ropg** [comment]
That bit of code looks confused indeed. Thanks! Will wait for Pull Request...
